import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { InconvoRuntimeProvider } from "@/app/InconvoRuntimeProvider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "assistant-ui Starter App",
  description: "Generated by create-assistant-ui",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <InconvoRuntimeProvider>
          <SidebarProvider>
            <AppSidebar />
            {children}
          </SidebarProvider>
        </InconvoRuntimeProvider>
      </body>
    </html>
  );
}
